### ISSUE TITLE
Support also a variant of text objects including leading/trailing blank lines like ap/ip

### ISSUE THREAD

**Issue by kana** [kana/vim-textobj-function#10]
Derived from #8.

> > By the way, I noticed that for the 'a' objects you don't select empty lines after the functions, like what for example the 'ap' object does. Is that intentional? I think it would be more consistent with Vim's normal text objects to include the empty lines.
> 
> Yes, it is intentional.  Vim's built-in text objects can be classified into two groups.  Some text objects like `ap`/`ip` include also leading/trailing spaces, while other text objects like `at`/`it` don't include such spaces.  When I began to write vim-textobj-function, I thought these text objects are classified into the latter group.
> 
> But it might be better to provide also a variant of function text objects as you suggest, and to let users choose which variant to use.

**Comment by nelstrom** [comment]
I had [a similar pull request](https://github.com/nelstrom/vim-textobj-rubyblock/pull/18) on textobj-rubyblock recently.

**Comment by nelstrom** [comment]
I get how `af` and `aF` work, but is there any difference between `if` and `iF`?

**Comment by kana** [comment]
`if` selects the code inside a function, while `iF` selects a whole function.  For example, if we edit the following Vim script file:

``` vim
let Foo = 0
function Foo()
  return 1
  return 2  " The current line.
  return 3
endfunction

let Bar = 0
function Bar()
  return 4
  return 5
  return 6
endfunction
...
```

Each function text object will select the following ranges:

```
            | let Foo = 0
aF iF af    | function Foo()
aF iF af if |   return 1
aF iF af if |   return 2  " The current line.
aF iF af if |   return 3
aF iF af    | endfunction
aF          | 
            | let Bar = 0
            | function Bar()
            |   return 4
            |   return 5
            |   return 6
            | endfunction
            | ...
```
