### ISSUE TITLE
Goto prev/next function / define move-p/move-n

### ISSUE THREAD

**Issue by blueyed** [kana/vim-textobj-function#16]
I think it would be nice to have mappings to go to the previous/next function by default.

That would probably mean to define a pattern or function for each file type.

I've done this a while ago for the textobj-python plugin (https://github.com/bps/vim-textobj-python/blob/6d5f367f3b099b3fd36d48547a7cc612bfeeba29/after/ftplugin/python/textobj-python.vim#L59-L61), but it seems that it should be provided by textobj-function itself.

As for the default mapping, `[f` and `]f` is already used by the unimpaired plugin:

> nmap ]f <Plug>unimpairedDirectoryNext
> nmap [f <Plug>unimpairedDirectoryPrevious

While at it, I am not sure about the integration with textobj-function withing textobj-python, which uses internal knowledge of textobj-function (https://github.com/bps/vim-textobj-python/blob/6d5f367f3b099b3fd36d48547a7cc612bfeeba29/after/ftplugin/python/textobj-python.vim#L25-L35).

**Comment by snoblenet** [comment]
This would be awesome. Also to go to the start or end of the function you're currently within.

**Comment by kana** [comment]
Do you know `[[`, `[m` and other key mappings which are defined provided by default, and the fact that most of filetype plugins override the key mappings to jump to proper objects in their languages?  That's why I don't have any interest to add such functionality into vim-textobj-function.

**Comment by blueyed** [comment]
@kana 
True. `[[` and `[m` gets set for Python filetypes, but it includes classes, so it might be good to have something more deterministic.  OTOH this is more an issue with Python's filetype plugin then.

Closing.

**Comment by snoblenet** [comment]
Unfortunately, `[[` and `]]` in JavaScript take you to the start and end of the outermost function, which often just means the start and end of the file, while `[m` and `]m` are too unergonomic to ever come naturally. But your tip was a good one, and I'm now very happy with this solution:
```
  autocmd BufEnter *.js,*.jsx nnoremap [[ [m
  autocmd BufEnter *.js,*.jsx nnoremap ]] ]m
  autocmd BufEnter *.js,*.jsx nnoremap [m [[
  autocmd BufEnter *.js,*.jsx nnoremap ]m [[
```
