### ISSUE TITLE
Unknown function: textobj#user#plugin

### ISSUE THREAD

**Issue by mbadran** [kana/vim-textobj-function#4]
Hi,

All of your text-object plugins produce the following error when I startup Vim:

Error detected while processing /Users/mohammed/Documents/projects/dotvim/bundle/vim-textobj-fold/plugin/textobj/fold.vim:
line   43:
E117: Unknown function: textobj#user#plugin 

Thanks.

**Comment by kana** [comment]
RTFM.

**Comment by Kidman1670** [comment]
The solution is install textobj-function-user plugin (https://github.com/kana/vim-textobj-user). this line in line 70 of the manual. Why dont just put it in the README.md?
I think the author just put all the plugin in to one, or spend sometime to add to README.md, plaese stop "RTFM", it seem so annoy
